/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_browser_CefSharedTexture_N */

#ifndef _Included_org_cef_browser_CefSharedTexture_N
#define _Included_org_cef_browser_CefSharedTexture_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_browser_CefSharedTexture_N
 * Method:    N_BindD3D11Texture
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL
Java_org_cef_browser_CefSharedTexture_1N_N_1BindD3D11Texture(JNIEnv*,
                                                             jclass,
                                                             jlong,
                                                             jint,
                                                             jint);

/*
 * Class:     org_cef_browser_CefSharedTexture_N
 * Method:    N_BindDmaBuf
 * Signature: (III[I[I[JJ)J
 */
JNIEXPORT jlong JNICALL
Java_org_cef_browser_CefSharedTexture_1N_N_1BindDmaBuf(JNIEnv*,
                                                       jclass,
                                                       jint,
                                                       jint,
                                                       jint,
                                                       jintArray,
                                                       jintArray,
                                                       jlongArray,
                                                       jlong);

/*
 * Class:     org_cef_browser_CefSharedTexture_N
 * Method:    N_ReleaseDmaBuf
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_org_cef_browser_CefSharedTexture_1N_N_1ReleaseDmaBuf(JNIEnv*,
                                                          jclass,
                                                          jlong);

#ifdef __cplusplus
}
#endif
#endif
