name: Build java-cef 5359

on:
  push:
  workflow_dispatch:

jobs:
  java-cef-linux:
    runs-on: [ubuntu-20.04]
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Install deps and build
        run: |
          sudo apt update
          sudo apt install build-essential g++ cmake ninja-build openjdk-17-jdk python3 libgtk2.0-dev -y
          mkdir jcef_build && cd jcef_build
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export JAVA_INCLUDE_PATH=/usr/lib/jvm/java-17-openjdk-amd64/include
          cmake -G "Ninja" -DPROJECT_ARCH=${{ matrix.platform }} -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          mv native/Release linux_${{ matrix.platform }}
          strip linux_${{ matrix.platform }}/libcef.so
          tar -czf linux_${{ matrix.platform }}.tar.gz linux_${{ matrix.platform }}
          sha256sum linux_${{ matrix.platform }}.tar.gz > linux_${{ matrix.platform }}.tar.gz.sha256
      - uses: actions/upload-artifact@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          name: 'linux_${{ matrix.platform }}'
          path: |
            jcef_build/linux_${{ matrix.platform }}.tar.gz
            jcef_build/linux_${{ matrix.platform }}.tar.gz.sha256
          if-no-files-found: error

  java-cef-windows:
    runs-on: [windows-2022]
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: |
          mkdir jcef_build && cd jcef_build
          cmake -G "Ninja" -DPROJECT_ARCH=${{ matrix.platform }} -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          cd native
          ren Release windows_${{ matrix.platform }}
          cd ..
          move native/windows_${{ matrix.platform }} windows_${{ matrix.platform }}
          tar -czf windows_${{ matrix.platform }}.tar.gz windows_${{ matrix.platform }}
          Get-FileHash -Algorithm SHA256 -Path "windows_${{ matrix.platform }}.tar.gz" | Out-File "windows_${{ matrix.platform }}.tar.gz.sha256"
      - uses: actions/upload-artifact@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          name: 'windows_${{ matrix.platform }}'
          path: |
            jcef_build/windows_${{ matrix.platform }}.tar.gz
            jcef_build/windows_${{ matrix.platform }}.tar.gz.sha256
          if-no-files-found: error

  java-cef-macos:
    runs-on: [macos-13]
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: |
          brew install ninja
          brew install coreutils
          sudo xcode-select -s /Applications/Xcode.app
          mkdir jcef_build && cd jcef_build
          cmake -G "Ninja" -DPROJECT_ARCH=${{ matrix.platform }} -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          mv native/Release macos_${{ matrix.platform }}
          tar -czf macos_${{ matrix.platform }}.tar.gz macos_${{ matrix.platform }}
          sha256sum macos_${{ matrix.platform }}.tar.gz > macos_${{ matrix.platform }}.tar.gz.sha256
      - uses: actions/upload-artifact@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          name: 'macos_${{ matrix.platform }}'
          path: |
            jcef_build/macos_${{ matrix.platform }}.tar.gz
            jcef_build/macos_${{ matrix.platform }}.tar.gz.sha256
          if-no-files-found: error
