name: Build java-cef

on:
  push:
  workflow_dispatch:

jobs:

  java-cef-windows:
    runs-on: [windows-2022]
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: |
          mkdir jcef_build && cd jcef_build
          cmake -G "Ninja" -DPROJECT_ARCH=${{ matrix.platform }} -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          cd native
          ren Release windows_${{ matrix.platform }}
          cd ..
          move native/windows_${{ matrix.platform }} windows_${{ matrix.platform }}
          python3 ../.github/workflows/scripts/generate_hash.py windows_${{ matrix.platform }}
          mv windows_${{ matrix.platform }}/.hash ./
          tar -czf windows_${{ matrix.platform }}.tar.gz windows_${{ matrix.platform }} .hash
          Get-FileHash -Algorithm SHA256 -Path "windows_${{ matrix.platform }}.tar.gz" | Out-File "windows_${{ matrix.platform }}.tar.gz.sha256"
      - uses: actions/upload-artifact@v4
        with:
          name: 'windows_${{ matrix.platform }}'
          path: |
            jcef_build/windows_${{ matrix.platform }}.tar.gz
            jcef_build/windows_${{ matrix.platform }}.tar.gz.sha256
          if-no-files-found: error
